# Railway deployment configuration
# This tells Railway how to deploy your backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python app.py"
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
PORT = "8000"