blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/Vishesh0-7/Github-Analyzer/discussions
    about: Ask questions and discuss ideas with the community